# Generated by Django 5.0.1 on 2024-02-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delete',
            fields=[
                ('student', models.CharField(max_length=155)),
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('classroom', models.IntegerField()),
            ],
            options={
                'db_table': 'helo',
                'managed': True,
            },
        ),
    ]
