# Generated by Django 5.0.1 on 2024-02-17 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deleteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delete',
            options={},
        ),
    ]
