# Generated by Django 5.0.1 on 2024-02-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deleteapp', '0002_alter_delete_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delete',
            options={'managed': True},
        ),
    ]
